export const SET_USERNAME = 'SET_USERNAME';
export const POST_LOGIN = 'POST_LOGIN';
export const SET_LOGIN_CALLBACK = 'SET_LOGIN_CALLBACK';

export const POST_CREATE_CAR = 'POST_CREATE_CAR';
export const SET_CREATE_CAR_CALLBACK = 'SET_CREATE_CAR_CALLBACK';
export const GET_CARS = 'GET_CARS';
export const SET_GET_CARS_CALLBACK = 'SET_GET_CARS_CALLBACK';

export const GET_ORDERS = 'GET_ORDERS';
export const SET_GET_ORDERS_CALLBACK = 'SET_GET_ORDERS_CALLBACK';

export const POST_CREATE_ORDERS = 'POST_CREATE_ORDERS';
export const SET_CREATE_ORDERS_CALLBACK = 'SET_CREATE_ORDERS_CALLBACK';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
